const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFile}=require('node:child_process');
const PYTHON=require('./runtime.cjs').python;
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function createSearch(store){const db=store.db,root=fs.realpathSync(path.dirname(store.dbPath));
 db.exec(`CREATE TABLE IF NOT EXISTS asset_text_meta(project TEXT,asset TEXT,hash TEXT,status TEXT,message TEXT,updated TEXT,PRIMARY KEY(project,asset));
 CREATE TABLE IF NOT EXISTS asset_text_chunks(id INTEGER PRIMARY KEY AUTOINCREMENT,project TEXT,asset TEXT,hash TEXT,ordinal INTEGER,locator TEXT,page INTEGER,text TEXT);
 CREATE VIRTUAL TABLE IF NOT EXISTS asset_text_fts USING fts5(text,content='asset_text_chunks',content_rowid='id',tokenize='trigram');
 CREATE TRIGGER IF NOT EXISTS asset_text_ai AFTER INSERT ON asset_text_chunks BEGIN INSERT INTO asset_text_fts(rowid,text)VALUES(new.id,new.text);END;
 CREATE TRIGGER IF NOT EXISTS asset_text_ad AFTER DELETE ON asset_text_chunks BEGIN INSERT INTO asset_text_fts(asset_text_fts,rowid,text)VALUES('delete',old.id,old.text);END;`);
 function owner(project){const r=store.get(project);if(!r)throw Error('找不到项目');return r.state.assetsProject||project}
 function asset(project,id){const a=store.assets(owner(project)).find(a=>a.id===id);if(!a)throw Error('素材不属于当前项目');return a}
 function check(a){const base=store.projects().find(p=>p.id===a.project)?.root||root,fp=fs.realpathSync(a.path),rel=path.relative(fs.realpathSync(base),fp);if(rel.startsWith('..')||path.isAbsolute(rel))throw Error('素材路径超出项目资料库');const stat=fs.statSync(fp);if(stat.size>20*1024*1024)throw Error('文件超过20MB');if(hash(fs.readFileSync(fp))!==a.sha256)throw Error('原文件已变化，旧定位需核对；请将新版作为新素材导入，保留旧版本');return fp}
 function list(project){return store.assets(owner(project)).map(a=>{const m=db.prepare('SELECT * FROM asset_text_meta WHERE project=? AND asset=?').get(owner(project),a.id);return {assetId:a.id,name:a.name,sourceHash:a.sha256,status:m?.status||'unindexed',message:m?.message||'尚未建立文字索引',updatedAt:m?.updated}})}
 const jobs=new Map();
 async function index(project,id){const a=asset(project,id),key=a.project+':'+id;if(jobs.has(key))return jobs.get(key);const job=(async()=>{let data;try{const fp=check(a);const existing=db.prepare('SELECT * FROM asset_text_meta WHERE project=? AND asset=?').get(a.project,id);if(existing?.status==='ready'&&existing.hash===a.sha256)return {...existing,assetId:id,name:a.name,sourceHash:a.sha256,chunks:db.prepare('SELECT count(*) AS n FROM asset_text_chunks WHERE project=? AND asset=?').get(a.project,id).n};data=await new Promise(resolve=>execFile(PYTHON,[path.join(__dirname,'extract_asset.py'),fp],{windowsHide:true,timeout:60000,maxBuffer:24000000,encoding:'utf8'},(err,out)=>{if(err)return resolve({status:'error',message:'文字提取未完成：'+(err.code||err.message),chunks:[]});try{resolve(JSON.parse(out))}catch{resolve({status:'error',message:'文字提取结果无法读取',chunks:[]})}}));check(a)}catch(e){data={status:'error',message:e.code==='EPERM'?'无法启动文字提取程序，请从本机终端启动服务后重试':e.message,chunks:[]}}
 db.exec('BEGIN IMMEDIATE');try{db.prepare('DELETE FROM asset_text_chunks WHERE project=? AND asset=?').run(a.project,id);for(const [i,c]of data.chunks.entries())db.prepare('INSERT INTO asset_text_chunks(project,asset,hash,ordinal,locator,page,text)VALUES(?,?,?,?,?,?,?)').run(a.project,id,a.sha256,i,c.locator,c.page||null,c.text);db.prepare('INSERT OR REPLACE INTO asset_text_meta VALUES(?,?,?,?,?,?)').run(a.project,id,a.sha256,data.status,data.message,new Date().toISOString());db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return {assetId:id,name:a.name,status:data.status,message:data.message,chunks:data.chunks.length,sourceHash:a.sha256};})();jobs.set(key,job);try{return await job}finally{jobs.delete(key)}}
 function search(project,query,limit=30){query=String(query||'').trim();if(!query||query.length>200)throw Error('请输入1—200字的查询词');limit=Math.min(50,Math.max(1,Number(limit)||30));const pid=owner(project),fts=[...query].length>=3;const rows=fts?db.prepare('SELECT c.* FROM asset_text_fts f JOIN asset_text_chunks c ON c.id=f.rowid WHERE asset_text_fts MATCH ? AND c.project=? ORDER BY c.asset,c.ordinal LIMIT ?').all('"'+query.replaceAll('"','""')+'"',pid,limit+1):db.prepare('SELECT * FROM asset_text_chunks WHERE project=? AND instr(lower(text),lower(?))>0 ORDER BY asset,ordinal LIMIT ?').all(pid,query,limit+1);
 const assets=new Map(store.assets(pid).map(a=>[a.id,a])),checked=new Map();const results=rows.slice(0,limit).map(c=>{const a=assets.get(c.asset);if(!checked.has(c.asset)){try{check(a);checked.set(c.asset,null)}catch(e){checked.set(c.asset,e.message)}}const i=c.text.toLowerCase().indexOf(query.toLowerCase()),start=Math.max(0,i-100);return {chunkId:c.id,assetId:c.asset,name:a?.name,sourceHash:c.hash,locator:c.locator,page:c.page,excerpt:c.text.slice(start,start+400),stale:checked.get(c.asset)||null}});return {query,results,hasMore:rows.length>limit,indexStatus:list(project),note:'按原文词句匹配，未检索到不代表资料不存在；查看索引状态与未提取内容。'}}
 function read(project,id){const pid=owner(project),c=db.prepare('SELECT * FROM asset_text_chunks WHERE id=? AND project=?').get(id,pid);if(!c)throw Error('找不到当前项目的文字片段');const a=asset(project,c.asset);check(a);const context=db.prepare('SELECT id,ordinal,locator,page,text FROM asset_text_chunks WHERE project=? AND asset=? AND ordinal BETWEEN ? AND ? ORDER BY ordinal').all(pid,c.asset,Math.max(0,c.ordinal-1),c.ordinal+1);return {assetId:a.id,name:a.name,sourceHash:c.hash,chunkId:c.id,locator:c.locator,page:c.page,text:c.text,context,sourcePath:a.path,downloadUrl:'/api/file?project='+encodeURIComponent(a.project)+'&id='+encodeURIComponent(a.id),pdfUrl:path.extname(a.name).toLowerCase()==='.pdf'?'/api/asset-pdf?project='+encodeURIComponent(project)+'&assetId='+encodeURIComponent(a.id)+'#page='+(c.page||1):null}}
 return {index,search,read,list,asset,check};}
module.exports={createSearch};
