const relations=require('./relations');
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
function values(s){const m=new Map();m.set('paper',s.paper);m.set('goal',s.blueprint.goal);m.set('colors',s.colors);for(const [group,rows]of [['node',s.blueprint.nodes],['decision',s.knowledge],['evidence',s.evidence||[]]])for(const row of rows)m.set(group+':'+row.id,row);
 for(const [group,obj]of [['claim',s.claimLinks||{}],['paragraph',s.manuscript?.edits||{}],['comment',s.overrides||{}]])for(const [id,v]of Object.entries(obj))m.set(group+':'+id,v);return m}
function info(store,projectId,id){const r=store.get(projectId);if(!r)throw Error('项目不存在');const d=(r.state.discussions||[]).find(d=>d.id===id);if(!d)throw Error('讨论成果不存在');const at=revision=>{const row=store.db.prepare('SELECT body FROM revisions WHERE project_id=? AND revision=?').get(projectId,revision);if(!row)throw Error('历史快照缺失，不能恢复');return JSON.parse(row.body)};const prev=at(d.revision-1),next=at(d.revision);const before=values(prev),after=values(next),now=values(r.state);for(const op of d.operations||[])if(op.operation==='review_impact'){for(const [map,state]of [[before,prev],[after,next],[now,r.state]])map.set('impact:'+op.id,(state.impacts||[]).find(i=>i.id===op.id));}const changes=[];for(const key of new Set([...before.keys(),...after.keys()]))if(!same(before.get(key),after.get(key)))changes.push({key,before:before.get(key)??null,after:after.get(key)??null,conflict:!same(after.get(key),now.get(key))});
 const reviews=(r.state.discussionReviews||[]).filter(v=>v.discussionId===id);return {projectId,revision:r.revision,discussion:d,changes,reviews,status:reviews.at(-1)?.action||'submitted',conflicts:changes.filter(c=>c.conflict).map(c=>c.key)};}
function set(s,key,value){if(key==='paper'){if(value===null)delete s.paper;else s.paper=value;return}if(key==='goal'){s.blueprint.goal=value;return}if(key==='colors'){s.colors=value;return}const sep=key.indexOf(':'),group=key.slice(0,sep),id=key.slice(sep+1);const arrays={node:s.blueprint.nodes,decision:s.knowledge,evidence:s.evidence||=[],impact:s.impacts||=[]};if(arrays[group]){const arr=arrays[group],i=arr.findIndex(x=>x.id===id);if(value===null){if(i>=0)arr.splice(i,1)}else if(i>=0)arr[i]=value;else arr.push(value);return}const maps={claim:s.claimLinks||={},paragraph:(s.manuscript||={edits:{},changes:[]}).edits,comment:s.overrides};if(value===null)delete maps[group][id];else maps[group][id]=value;}
function perform(store,a){if(!['accepted','needs_changes','restored'].includes(a.action)||!a.note?.trim())throw Error('请选择处理方式并说明理由');const view=info(store,a.projectId,a.discussionId);return store.mutate(a.projectId,a.baseRevision,a.requestId,{tool:'discussion-review',...a},s=>{if(view.status==='restored')throw Error('本组已恢复，原提交仍保留');
 if(a.action==='restored'){
  if(!view.changes.length)throw Error('这次只有讨论记录，没有可恢复的内容');if(view.conflicts.length)throw Error('以下内容已有后续修改，恢复未执行：'+view.conflicts.join('、'));
  const changedNodes=view.changes.filter(c=>c.key.startsWith('node:')).map(c=>c.key.slice(5));if(changedNodes.some(id=>s.blueprint.drafts[id]))throw Error('关联章节有未提交草稿，请先处理');
  // A restore keeps later unrelated edits, original change logs and all snapshots.
  for(const c of view.changes)set(s,c.key,structuredClone(c.before));
  const source=relations.sourceFor(store,s);for(const e of s.evidence||[])relations.validateTargets(e.targets,s,source);for(const k of s.knowledge){if(k.targets)relations.validateTargets(k.targets,s,source);if(k.supersedes&&!s.knowledge.some(d=>d.id===k.supersedes))throw Error('后续决定仍引用将恢复移出的决定，恢复未执行');}
  for(const c of Object.values(s.claimLinks||{})){if([...c.support,...c.counter].some(id=>!(s.evidence||[]).some(e=>e.id===id)))throw Error('后续主张仍引用本次新增证据，恢复未执行');if(c.nodes.some(id=>!s.blueprint.nodes.some(n=>n.id===id)))throw Error('后续主张仍引用本次章节，恢复未执行')}
  const time=new Date().toISOString();s.manuscript||={edits:{},changes:[]};const paragraphs=view.changes.filter(c=>c.key.startsWith('paragraph:')).map(c=>{const id=c.key.slice(10),original=source.paragraphs.find(p=>p.id===id)?.text||'';return {paragraphId:id,before:c.after?.text??original,after:c.before?.text??original}});if(paragraphs.length)s.manuscript.changes.push({revision:a.baseRevision+1,time,reason:'恢复讨论成果：'+a.note,actor:'用户',comments:[],paragraphs});
 }
 s.discussionReviews||=[];s.discussionReviews.push({discussionId:a.discussionId,action:a.action,note:a.note,time:new Date().toISOString(),revision:a.baseRevision+1,actor:'用户'});s.events.unshift({time:new Date().toISOString(),text:'用户'+({accepted:'接受',needs_changes:'要求继续修改',restored:'恢复'}[a.action])+'讨论成果：'+view.discussion.title+'；'+a.note});});}
module.exports={info,perform};
