const INITIAL_TEMPLATE={format:'xuzhang-project-v1',项目名称:'我的新项目',作品类型:'论文 / 开题报告 / 视频 / 其他',目标:'希望作品解决什么问题，达到什么效果',受众:'作品面向谁',内容:[{名称:'引言',标题:'提出需要解决的问题',问题:'这里要回答什么？',核心表达:'希望读者或观众理解什么？',依据:'事实、资料或素材的位置；不确定的信息请标注待核对',推理:'这些依据如何支持想法？',表达方式:'正文、画面、叙述顺序或节奏安排',草稿:'把已经讨论出的这一部分草稿放在这里，可以留空。'}],写作要求:['需要持续遵守的表达要求'],未决问题:['仍需讨论或查证的事项']};
const ORIGINAL_PAPER={...PAPER}, ORIGINAL_PARAGRAPHS={...P}, PROJECTS_KEY=KEY+'-projects';
let projectCatalog={},remoteProjects=[],assetList=[],assetError='',importCandidate=null,assetBusy=false;
try{projectCatalog=JSON.parse(localStorage.getItem(PROJECTS_KEY)||'{}')}catch{}
function cacheProject(){try{localStorage.setItem(KEY,JSON.stringify(state));const key=state.project?.id||'demo';projectCatalog[key]=JSON.parse(JSON.stringify(state));localStorage.setItem(PROJECTS_KEY,JSON.stringify(projectCatalog))}catch{toast('项目副本保存失败，请导出记录')}}
function applyBaseSource(){if(!state.project?.input){Object.assign(PAPER,ORIGINAL_PAPER);Object.keys(P).forEach(k=>delete P[k]);Object.assign(P,ORIGINAL_PARAGRAPHS);return}const input=state.project.input,ps=[];input.内容.forEach((n,i)=>{const id='import-'+i;ps.push({id,type:'heading',text:n.名称,runs:[{start:0,end:n.名称.length,text:n.名称}],maths:[],images:[],level:1});(n.草稿||'（这一部分尚无草稿）').split(/\n\s*\n/).forEach((t,j)=>{ps.push({id:id+'-'+j,type:'paragraph',text:t,runs:[{start:0,end:t.length,text:t}],maths:[],images:[],level:0})})});Object.keys(P).forEach(k=>delete P[k]);ps.forEach(p=>P[p.id]=p);Object.assign(PAPER,{title:input.项目名称,sha256:state.project.sha256||state.project.id,source:'初始化模板导入 / '+state.project.root,blocks:ps,paragraphs:ps,comments:[],images:{},outline:ps.filter(p=>p.type==='heading').map(p=>({id:p.id,title:p.text,level:1})),counts:{paragraphs:ps.length,nonemptyParagraphs:ps.length,tables:0,images:0,equations:0,comments:0}})}
function stateFromProject(m){const nodes=m.input.内容.map((n,i)=>({id:'I-'+i,part:n.名称,title:n.标题||n.名称,question:n.问题||'',claim:n.核心表达||'',evidence:n.依据||'',logic:n.推理||'',expression:n.表达方式||'',anchor:'import-'+i+'-0',comments:[]}));return{...(PaperPresets.initial(m.input)?{paper:PaperPresets.initial(m.input)}:{}),project:m,comments:[],overrides:{},colors:[],knowledge:[...(m.input.写作要求||[]).map((s,i)=>({id:'R'+i,kind:'写作原则',title:s,body:s,source:'初始化模板',anchor:'',status:'待核对'})),...(m.input.未决问题||[]).map((s,i)=>({id:'Q'+i,kind:'待讨论',title:s,body:s,source:'初始化模板',anchor:'',status:'待核对'}))],events:[],blueprint:{goal:m.input.目标,nodes,changes:[],drafts:{}}}}
function activateProject(s){cacheProject();state=s;activeBlueprint=state.blueprint.nodes[0].id;blueprintComment=null;selected='';selection=null;composer=false;applyProjectSource();page='blueprint';assetList=[];assetError='';localStorage.setItem(KEY,JSON.stringify(state));shell();window.scrollTo(0,0)}
async function api(url,data){const r=await fetch(url,data?{method:'POST',headers:{'Content-Type':'application/json','X-Xuzhang-Client':'local-ui'},body:JSON.stringify(data)}:{}).catch(()=>{throw Error('本地服务连接中断，修改已保留，请恢复服务后重试')});let j;try{j=await r.json()}catch{throw Error('需要重新启动本地服务后再导入')}if(!r.ok)throw Object.assign(Error(j.error||'操作失败'),{status:r.status});return j}
function projectControls(){const el=document.querySelector('header .top-actions')||document.querySelector('header .actions');if(!el)return;el.insertAdjacentHTML('afterbegin',`${btn("切换项目","project-switch","class=\"primary\"")}<select id="project-picker" aria-label="切换项目" hidden><option value="demo">论文示例</option>${Object.entries(projectCatalog).filter(([k])=>k!=='demo').map(([k,v])=>`<option value="${esc(k)}" ${state.project?.id===k?'selected':''}>${esc(v.project.name)}</option>`).join('')}${remoteProjects.filter(m=>!projectCatalog[m.id]).map(m=>`<option value="${m.id}" ${state.project?.id===m.id?'selected':''}>${esc(m.name)} · 初始稿</option>`).join('')}</select>${btn('初始化导入','init-open')}`);const title=state.project?.name||'续章入门示例';document.querySelector('.project h3').textContent=title;document.querySelector('header>span').textContent=title+' / 项目工作台';if(state.project){const badge=document.querySelector('.project .tag');badge.textContent='导入项目 · 工作副本';document.querySelector('.notice>span').textContent='蓝图与草稿来自初始化模板 · 文件保存在本机';}}
async function projectSwitchDialog(){
 try{const [data,connection]=await Promise.all([api('/api/state'),api('/api/connection')]);
 $('#modal').innerHTML=`<h2>切换项目</h2><p>当前网页：<strong>${esc(state.project?.name||'续章入门示例')}</strong></p><div class="project-choices">${data.projects.map(r=>`<section class="project-choice"><div><strong>${esc(r.state.project?.name||'续章入门示例')}</strong><small>${esc(r.state.project?.input?.作品类型||'论文')} · ${r.state.blueprint.nodes.length} 个部分</small></div>${r.id===currentId()?'<span class="tag green">当前项目</span>':btn('进入项目','project-enter',`data-id="${esc(r.id)}"`)}</section>`).join('')}</div><h3>Codex 正在接触的项目</h3><p>每条连接单独选择工作项目。网页切换不会改变正在进行的 Codex 工作。</p>${connection.clients.length?connection.clients.map(c=>`<p class="source">${esc(c.client)}：<strong>${esc(c.projectName||'尚未选择项目（旧连接需重载）')}</strong></p>`).join(''):'<p class="muted">暂无连接。连接后在 Codex 中说明要处理哪个项目。</p>'}<div class="actions">${btn('新建 / 导入项目','project-create')}${btn('关闭','close')}</div>`;$('#modal').showModal();
 }catch(e){toast(e.message)}
}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='project-switch')await projectSwitchDialog();if(b.dataset.action==='project-create'){$('#modal').close();initDialog()}if(b.dataset.action==='project-enter'){b.disabled=true;await switchProject(b.dataset.id);if(currentId()===b.dataset.id)$('#modal').close();else b.disabled=false;}});
function downloadJSON(obj,name){const u=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function selectedInitTemplate(){return $('#init-preset').value==='legacy'?structuredClone(INITIAL_TEMPLATE):PaperPresets.template($('#init-preset').value)}
async function initDialog(){let defaults;try{defaults=await api('/api/storage-defaults')}catch(e){toast(e.message);return}importCandidate=null;$('#modal').innerHTML=`<h2>从一次对话开始一个项目</h2><p>在Codex里讨论目标和草稿，按模板整理后导入。每次创建独立项目，现有内容保留。</p><section class="card"><h3>先确认资料保存位置</h3><p id="init-storage-error" role="alert" style="color:#b5463c"></p><label for="init-directory">当前创作项目文件夹（完整路径）</label><input id="init-directory" value="${esc(state.project?.projectDirectory||defaults.projectDirectory)}"><p class="muted">${esc(defaults.note)} 原文件会分类保存到此文件夹下的“续章资料 / 独立项目编号”，同一文件夹中的作品也各自分开。初始化会在此文件夹生成“打开续章工作站”入口，双击可启动并进入本项目。</p><label><input type="checkbox" id="init-storage-confirmed"> 我确认在上述项目文件夹中保存资料</label><small class="asset-path">讨论、批注和版本数据库：${esc(defaults.database)}。备份时还需保留此数据库。</small></section><label for="init-preset">选择预设模板</label><select id="init-preset">${PaperPresets.presets.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}<option value="legacy">原有通用导入格式</option></select><p id="preset-description" class="muted">${esc(PaperPresets.presets[0].description)}</p><div class="actions">${btn('下载所选模板','init-template')}${btn('使用所选模板填写','init-fill')}</div><small>开题报告和视频模板尚未提供。切换选项不会覆盖下方已有内容。</small><label for="init-name">新项目名称</label><input id="init-name" placeholder="例如：我的研究论文"><label for="init-goal">希望解决的问题（可留空）</label><textarea id="init-goal" style="min-height:70px"></textarea><div class="actions">${btn("按模板准备新项目","init-blank","class=\"primary\"")}</div><h3>或导入 Codex 整理好的资料</h3><details><summary>给Codex的整理要求</summary><p>请将我们的讨论整理为续章初始化模板，保留目标、受众、各部分的想法与草稿。未确认内容标明待核对，未知字段留空，不编造事实。输出有效的JSON文件，字段结构与下载模板一致。</p></details><label for="init-file">选择模板文件（JSON，最多2MB）</label><input id="init-file" type="file" accept=".json,application/json"><label for="init-text">或粘贴模板内容</label><textarea id="init-text" placeholder="粘贴Codex整理好的JSON"></textarea><div id="init-result" role="status"></div><div class="actions">${btn('取消','close')}${btn('检查导入内容','init-check','class="primary"')}</div>`;$('#modal').showModal()}
function checkImport(v){if(v?.论文设置)PaperPresets.validate(v.论文设置);if(!v||v.format!=='xuzhang-project-v1')throw Error('请使用下载的初始化模板');if(typeof v.项目名称!=='string'||!v.项目名称.trim()||v.项目名称.length>120)throw Error('请填写项目名称，最多120字');if(typeof v.目标!=='string')throw Error('目标需要是文字');if(!Array.isArray(v.内容)||!v.内容.length||v.内容.length>100)throw Error('需要1—100个内容部分');for(const n of v.内容){if(!n||typeof n.名称!=='string'||!n.名称.trim())throw Error('每个内容部分需要名称');for(const k of ['名称','标题','问题','核心表达','依据','推理','表达方式','草稿'])if(n[k]!==undefined&&(typeof n[k]!=='string'||n[k].length>100000))throw Error('字段“'+k+'”需要文字且不超过10万字')}return v}
function assetsView(){return head('素材与文件','保存原文件，记录用途，并关联到创作蓝图。')+assetSearchView()+`<div class="cards"><section class="card"><h2>导入素材</h2><p class="muted">单文件最多20MB，可多选。同名文件分开保存，原文件保持不动。</p><form id="asset-form"><label for="asset-category">放入哪个类别</label><select id="asset-category">${['参考资料','数据','图片','音视频','其他'].map(n=>`<option>${n}</option>`).join('')}</select><label for="asset-part">关联蓝图部分</label><select id="asset-part"><option value="">整个项目</option>${state.blueprint.nodes.map(n=>`<option value="${n.id}">${esc(n.part)}</option>`).join('')}</select><label for="asset-note">用途说明</label><textarea id="asset-note" placeholder="这份资料支持什么想法，或准备放在什么位置？"></textarea><label for="asset-files">选择文件</label><input type="file" id="asset-files" multiple required><div class="actions"><button class="primary" type="submit" ${assetBusy?'disabled':''}>${assetBusy?'正在保存…':'导入并保存文件'}</button></div><div id="asset-status" role="status">${esc(assetError)}</div></form></section><section class="card"><h2>结构化保存位置</h2><p class="asset-path">${esc(state.project?.root||state.assetsRoot||'首次创建项目时确认保存位置')}</p><div class="folder-list">00_项目 / 初始化信息<br>01_草稿 / 导入草稿<br>02_参考资料<br>03_数据<br>04_图片<br>05_音视频<br>06_其他</div><p class="muted">每份素材单独保存原文件、用途说明、关联部分和文件指纹。上传完成才登记为已导入。</p><div class="actions">${btn('打开资料库文件夹','library-open')}${btn('刷新文件列表','assets-refresh')}</div><p class="muted">此处保存素材与初始化文件；讨论、批注和版本保存在续章数据库中，备份时请同时保留。</p></section></div><div class="asset-list"><h2>已导入文件 · ${assetList.length}</h2>${assetList.map(a=>`<section class="card"><div class="actions"><span class="tag green">${esc(a.category)}</span><small>${(a.size/1024).toFixed(1)} KB · ${esc(state.blueprint.nodes.find(n=>n.id===a.part)?.part||'整个项目')}</small></div><h3>${esc(a.name)}</h3><p>${esc(a.note||'尚未填写用途')}</p><small class="asset-path">${esc(a.path)}</small><div class="actions">${btn('打开原文件','asset-open',`data-id="${esc(a.id)}"`)}${btn('在文件夹中显示','asset-reveal',`data-id="${esc(a.id)}"`)}<a class="asset-download" href="/api/file?project=${a.project}&id=${a.id}">下载原文件</a></div></section>`).join('')||'<p class="muted">还没有导入文件。</p>'}</div>`}
async function refreshAssets(){const current=currentId(),pid=state.project?.id||state.assetsProject;if(!pid){assetList=[];return}try{const list=await api('/api/assets?project='+pid),index=await api('/api/asset-index?project='+encodeURIComponent(current));if(current!==currentId())return;assetList=list;assetIndexRows=index;assetError=''}catch(e){if(current!==currentId())return;assetError=e.message}if(page==='assets')renderContent()}
async function ensureAssetProject(){if(state.project)return state.project.id;if(state.assetsProject)return state.assetsProject;await initDialog();throw Error('请先创建项目并确认保存位置，再导入素材')}
function readBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('无法读取文件 '+file.name));reader.readAsDataURL(file)})}
document.addEventListener('change',async e=>{if(e.target.id==='init-preset'){$('#preset-description').textContent=e.target.value==='legacy'?'保留旧导入格式，不附加论文规则。':PaperPresets.get(e.target.value).description;importCandidate=null;$('#init-result').textContent='选择已改变，输入内容保持原样。模板以导入内容中的论文设置为准。'}if(e.target.id==='init-file'){const f=e.target.files[0];if(!f)return;if(f.size>2*1024*1024){$('#init-result').textContent='初始化文件超过2MB';return}$('#init-text').value=await f.text();importCandidate=null;$('#init-result').textContent='文件已读取，请检查导入内容。'}if(e.target.id==='project-picker'){const k=e.target.value;const s=projectCatalog[k]||(remoteProjects.find(m=>m.id===k)?stateFromProject(remoteProjects.find(m=>m.id===k)):null);if(s)switchProject(k)} });
document.addEventListener('input',e=>{if(e.target.id==='init-directory'){$('#init-storage-confirmed').checked=false;if(importCandidate)delete importCandidate.requestId}if(e.target.id==='init-text'){importCandidate=null;$('#init-result').textContent='内容已变化，请重新检查。'}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;
if(a==='init-blank'){if(!$('#init-name').value.trim()){$('#init-result').textContent='请先填写新项目名称。';return}if($('#init-text').value.trim()){$('#init-result').textContent='下方已有导入内容，请先完成导入或重新打开窗口准备空白项目。';return}const t=selectedInitTemplate();t.项目名称=$('#init-name').value.trim();t.目标=$('#init-goal').value.trim();$('#init-text').value=JSON.stringify(t,null,2);document.querySelector('[data-action=init-check]').click();}else if(a==='init-fill'){try{const template=selectedInitTemplate();const raw=$('#init-text').value.trim();if(raw){const existing=JSON.parse(raw);if(existing.论文设置&&existing.论文设置.templateId!==template.论文设置?.templateId)throw Error('已有论文设置，请下载另一模板另建项目，或先自行修改输入内容');$('#init-text').value=JSON.stringify({...template,...existing,...(!existing.论文设置&&template.论文设置?{论文设置:template.论文设置}:{})},null,2)}else $('#init-text').value=JSON.stringify(template,null,2);importCandidate=null;$('#init-result').textContent='模板已填入。请填写项目名称、目标和已有资料，未知内容可留空。'}catch(err){$('#init-result').textContent=err.message}}else if(a==='init-open')initDialog();else if(a==='init-template')downloadJSON(selectedInitTemplate(),'续章_项目初始化模板.json');else if(a==='init-check'){try{if(new Blob([$('#init-text').value]).size>2*1024*1024)throw Error('初始化内容超过2MB');const incoming=JSON.parse($('#init-text').value);if(!incoming.论文设置&&$('#init-preset').value!=='legacy')incoming.论文设置=PaperPresets.context($('#init-preset').value);importCandidate=checkImport(incoming);$('#init-result').innerHTML=`<div class="bp-feedback"><h3>${esc(importCandidate.项目名称)}</h3><p>模板：${importCandidate.论文设置?esc(PaperPresets.get(importCandidate.论文设置.templateId).name):'原有通用格式'}</p><p>${esc(importCandidate.目标)}</p><p>${importCandidate.内容.length} 个部分：${importCandidate.内容.map(n=>esc(n.名称)).join('、')}</p><p>包含 ${importCandidate.内容.filter(n=>n.草稿?.trim()).length} 个部分的草稿。将创建新项目。</p>${btn('确认导入为新项目','init-commit','class="primary"')}</div>`}catch(e){importCandidate=null;$('#init-result').textContent='无法导入：'+e.message}}
else if(a==='init-commit'&&importCandidate){b.disabled=true;b.textContent='正在保存…';try{if(!$('#init-storage-confirmed').checked)throw Error('请先确认资料保存位置');importCandidate.requestId||=crypto.randomUUID();const m=await api('/api/projects',{...importCandidate,projectDirectory:$('#init-directory').value.trim(),storageConfirmed:true});const saved=(await api('/api/state')).projects.find(r=>r.id===m.id);if(!saved)throw Error('项目已创建，请重试载入');versions[m.id]=saved.revision;delete m.revision;const next=saved.state;projectCatalog[m.id]=next;if(!remoteProjects.some(p=>p.id===m.id))remoteProjects.push(m);activateProject(next);cacheProject();$('#modal').close();toast('已创建新项目，并在项目文件夹生成工作站入口')}catch(e){b.disabled=false;b.textContent='确认导入为新项目';$('#init-storage-error').textContent='导入未完成：'+e.message;$('#init-directory').focus()}}
else if(['library-open','asset-open','asset-reveal'].includes(a)){try{const project=state.project?.id||state.assetsProject;if(!project)throw Error('请先创建项目并确认保存位置');await api('/api/open-local',{project,assetId:a==='library-open'?undefined:b.dataset.id,mode:a==='asset-open'?'open':'reveal'});toast(a==='asset-open'?'已请求系统打开文件':'已请求系统打开文件夹')}catch(e){toast(e.message)}}
else if(a==='assets-refresh')await refreshAssets();else if(a==='nav'&&b.dataset.page==='assets')await refreshAssets();else if(a==='bp-remove'){if(state.blueprint.nodes.length<=1){toast('至少保留一个内容部分');return}const n=bpNode();state.blueprint.archived ||= [];state.blueprint.archived.push(structuredClone(n));state.blueprint.nodes=state.blueprint.nodes.filter(x=>x.id!==n.id);activeBlueprint=state.blueprint.nodes[0].id;save('归档蓝图部分：'+n.part);renderContent();toast('已归档，可在“恢复章节”中恢复')}else if(a==='bp-restore'){const n=state.blueprint.archived?.pop();if(!n){toast('没有已归档部分');return}state.blueprint.nodes.push(n);activeBlueprint=n.id;save('恢复蓝图部分：'+n.part);renderContent()}
});
document.addEventListener('submit',async e=>{if(e.target.id!=='asset-form')return;e.preventDefault();if(assetBusy)return;const files=[...$('#asset-files').files];if(!files.length)return;const category=$('#asset-category').value,part=$('#asset-part').value,note=$('#asset-note').value;assetBusy=true;const button=e.target.querySelector('button');button.disabled=true;$('#project-picker').disabled=true;let ok=0;try{const project=await ensureAssetProject();for(const file of files){$('#asset-status').textContent='正在保存并提取文字 '+file.name;if(!file.size)throw Error(file.name+' 是空文件');if(file.size>20*1024*1024)throw Error(file.name+' 超过20MB');await api('/api/assets',{project,category,part,note,name:file.name,data:await readBase64(file)});ok++}assetError='已保存 '+ok+' 个文件';save(assetError)}catch(e){assetError='已保存 '+ok+' 个文件；后续未完成：'+e.message}finally{assetBusy=false;if($('#project-picker'))$('#project-picker').disabled=false;const message=assetError;await refreshAssets();assetError=message;if(page==='assets')renderContent()}});
document.addEventListener('click',e=>{if(assetBusy&&e.target.closest('[data-action="nav"],[data-action="init-open"]')){e.preventDefault();e.stopImmediatePropagation();toast('文件正在保存，请完成后再切换')}},true);
applyProjectSource();

function applyProjectSource(){applyBaseSource();for(const [id,edit]of Object.entries(state.manuscript?.edits||{})){if(P[id])P[id]={...P[id],text:edit.text,runs:[{start:0,end:edit.text.length,text:edit.text}]}}PAPER.paragraphs=PAPER.paragraphs.map(p=>P[p.id]||p);PAPER.outline=PAPER.outline.map(o=>({...o,title:P[o.id]?.text||o.title}));}
function draftChanges(){return (state.manuscript?.changes||[]).slice().reverse().map(c=>`<section class="card"><span class="tag green">正文工作草稿 · 版本 ${c.revision}</span><h2>Codex 修改了 ${c.paragraphs.length} 段</h2><p>${esc(c.reason)}</p><small>${esc(c.time)} · 关联批注 ${esc(c.comments.join('、')||'无')}</small>${c.paragraphs.map(p=>`<h3>${esc(p.paragraphId)}</h3><div class="bp-diff"><div><small>修改前</small><p>${esc(p.before)}</p></div><div><small>修改后</small><p>${esc(p.after)}</p></div></div>${btn('查看当前段落','jump',`data-id="${esc(p.paragraphId)}"`)}`).join('')}</section>`).join('')}
