let relationTab='decisions';
const decisionLabel=k=>({active:'当前采用',candidate:'候选 · 待采用',superseded:'已被替代'}[k.lifecycle]||k.status);
function relationTargets(ts){return (ts||[]).map(t=>{const n=t.kind==='blueprint'?state.blueprint.nodes.find(n=>n.id===t.id):t.kind==='decision'?state.knowledge.find(n=>n.id===t.id):null;return `<span class="tag">${esc(n?.part||n?.title||t.id)}</span>`}).join(' ')}
function targetButton(t,label='查看关联位置'){if(t.kind==='claim')return btn('查看主张与证据','claim-open',`data-id="${esc(t.id)}"`);if(t.kind==='blueprint'&&!state.blueprint.nodes.some(n=>n.id===t.id))return '<span class="tag amber">关联章节已归档</span>';return t.kind==='blueprint'?btn(label,'bp-select',`data-id="${esc(t.id)}"`):t.kind==='paragraph'?btn(label,'jump',`data-id="${esc(t.id)}"`):t.kind==='comment'?btn(label,'comment',`data-id="${esc(t.id)}"`):btn(label,'relation-tab','data-tab="decisions"')}
function localEvidenceStatus(e){if(e.sourceType!=='paragraph')return '文件位置已登记 · 内容待核对';return P[e.sourceId]?.text===e.sourceText?'段落位置已核对':'来源正文已变化 · 需核对'}
function evidenceCard(e){return `<section class="card"><div class="actions"><span class="tag">${e.sourceType==='paragraph'?'正文段落':'导入文件'}</span><span class="tag amber">${esc(localEvidenceStatus(e))}</span></div><h2>${esc(e.title)}</h2><p><strong>支持什么：</strong>${esc(e.purpose)}</p><div class="quote">${esc(e.quote)}</div><p class="source">${esc(e.sourceName||e.sourceId)} · ${esc(e.locator)}</p>${e.sourcePath?`<p class="asset-path">${esc(e.sourcePath)}</p>`:''}<div class="actions">${relationTargets(e.targets)}</div><div class="actions">${e.sourceType==='paragraph'?btn('查看来源原文','jump',`data-id="${esc(e.sourceId)}"`):`<a class="asset-download" href="/api/file?project=${encodeURIComponent(state.assetsProject||currentId())}&id=${encodeURIComponent(e.sourceId)}">下载来源文件</a>`}${e.sourceChunkId?btn('查看提取原处','asset-hit',`data-chunk="${e.sourceChunkId}"`):''}${btn('核对 / 更新定位','evidence-form',`data-id="${esc(e.id)}"`)}</div>${e.history?.length?`<details><summary>定位历史 · ${e.history.length}</summary>${e.history.map(h=>`<p>${esc(h.locator)}<br>${esc(h.quote)}</p>`).join('')}</details>`:''}</section>`}
function relationsView(){const ds=state.knowledge.filter(k=>k.kind==='决定'||k.lifecycle),es=state.evidence||[],alerts=state.impacts||[],open=alerts.filter(i=>i.status!=='resolved');return head('决定、证据与影响','保留选择的来由，找到证据原处，知道变化以后还要检查哪里。')+`<div class="relation-summary"><div><b>${ds.filter(k=>k.lifecycle==='active').length}</b><span>当前采用的决定</span></div><div><b>${es.length}</b><span>已定位证据</span></div><div><b>${open.length}</b><span>待检查影响</span></div></div><div class="filters">${[['decisions','决定与替代'],['evidence','证据定位'],['impacts','变化影响 · '+open.length]].map(([id,name])=>btn(name,'relation-tab',`data-tab="${id}" class="${relationTab===id?'active':''}"`)).join('')}</div>`+(relationTab==='decisions'?`<div class="actions">${btn('＋ 记录决定','decision-form','class="primary"')}</div><p class="muted">新决定先作为候选。采用后旧决定退出当前采用列表，但原话、理由与替代链保留。</p><div class="cards">${ds.filter(k=>k.lifecycle!=='superseded').map(decisionCard).join('')||'<section class="card"><h2>把一次重要选择留下来</h2><p>例如评价指标、论证结构或表达原则。已有资料保持原状态，未自动认定为已采用决定。</p></section>'}</div><details class="relation-history"><summary>已被替代的决定 · ${ds.filter(k=>k.lifecycle==='superseded').length}</summary><div class="cards">${ds.filter(k=>k.lifecycle==='superseded').map(decisionCard).join('')}</div></details>`:relationTab==='evidence'?`<div class="actions">${btn('＋ 定位一条证据','evidence-form','class="primary"')}</div><p class="muted">记录来源原文、具体位置以及支撑哪个想法。页码和表格区域需自行核对；登记位置不代表已经验证证据结论。</p><div class="cards">${es.map(evidenceCard).join('')||'<section class="card"><h2>从一段原文或一份素材开始</h2><p>在作品中选中文字后可点击“定位为证据”，或在这里选择来源段落、导入文件。</p></section>'}</div>`:`<p class="muted">只沿已建立的关联提醒；未关联的摘要、结论或其他章节仍需人工检查。确认提醒不会确认批注或重写正文。</p><div class="impact-list">${open.slice().reverse().map(impactCard).join('')||'<section class="card"><h2>当前没有待检查提醒</h2><p>采用替代决定、修改证据、蓝图或正文后，这里会列出关联位置及检查理由。</p></section>'}</div><details class="relation-history"><summary>已检查记录 · ${alerts.length-open.length}</summary>${alerts.filter(i=>i.status==='resolved').slice().reverse().map(impactCard).join('')}</details>`)}
function decisionCard(k){const old=state.knowledge.find(n=>n.id===k.supersedes),next=state.knowledge.find(n=>n.id===k.supersededBy);return `<section class="card"><span class="tag ${k.lifecycle==='active'?'green':'amber'}">${esc(decisionLabel(k))}</span><h2>${esc(k.title)}</h2><p>${esc(k.body)}</p>${k.reason?`<p><strong>为什么：</strong>${esc(k.reason)}</p>`:''}<p class="source">来源：${esc(k.source)}<br>适用范围：${esc(k.scope||'未单独指定')}</p><div class="actions">${relationTargets(k.targets)}</div>${old?`<div class="relation-chain">替代前项：${esc(old.title)}<details><summary>比较旧内容</summary><p>${esc(old.body)}</p></details></div>`:''}${next?`<p class="relation-chain">后续采用：${esc(next.title)}</p>`:''}<div class="actions">${k.lifecycle==='candidate'?btn('比较并采用','decision-adopt',`data-id="${esc(k.id)}" class="primary"`):''}${k.lifecycle!=='superseded'?btn('提出替代决定','decision-form',`data-prior="${esc(k.id)}"`):''}</div></section>`}
function relationPath(k){const [kind,id]=k.split(':');return (kind==='blueprint'?state.blueprint.nodes.find(n=>n.id===id)?.part:kind==='decision'?state.knowledge.find(n=>n.id===id)?.title:kind==='evidence'?(state.evidence||[]).find(n=>n.id===id)?.title:kind==='paragraph'?P[id]?.text?.slice(0,35):kind==='comment'?'批注 '+id:null)||id}
function impactCard(i){return `<section class="card"><div class="actions"><span class="tag ${i.status==='resolved'?'green':'amber'}">${i.status==='resolved'?'已检查':i.status==='review'?'AI 已检查 · 待你确认':'需要检查'}</span><small>版本 ${i.revision}</small></div><h3>${esc(i.title)}</h3><p>${esc(i.reason)}</p><small class="impact-chain">${esc((i.pathLabels||i.chain.map(relationPath)).join(' → '))}</small>${i.note?`<div class="quote">检查结果：${esc(i.note)}</div>`:''}<div class="actions">${i.target.kind==='evidence'?btn('查看证据','relation-tab','data-tab="evidence"'):targetButton(i.target)}${i.status!=='resolved'?btn('记录检查结果','impact-review',`data-id="${esc(i.id)}"`):''}</div></section>`}
function targetFields(list=[]){return `<fieldset class="relation-targets"><legend>用在什么位置（可多选）</legend>${state.blueprint.nodes.map(n=>`<label><input type="checkbox" name="relation-node" value="${esc(n.id)}" ${list.some(t=>t.kind==='blueprint'&&t.id===n.id)?'checked':''}> ${esc(n.part)}</label>`).join('')}<label for="relation-paragraph">关联正文段落（可多选）</label><select id="relation-paragraph" multiple size="4">${PAPER.paragraphs.filter(p=>p.text).map(p=>`<option value="${esc(p.id)}" ${list.some(t=>t.kind==='paragraph'&&t.id===p.id)?'selected':''}>${esc(p.id+' · '+p.text.slice(0,55))}</option>`).join('')}</select><label for="relation-decision">关联决定或资料（可多选）</label><select id="relation-decision" multiple size="4">${state.knowledge.filter(k=>k.lifecycle!=='superseded').map(k=>`<option value="${esc(k.id)}" ${list.some(t=>t.kind==='decision'&&t.id===k.id)?'selected':''}>${esc(k.title)}</option>`).join('')}</select></fieldset>`}
function readTargets(existing=[]){const list=[...document.querySelectorAll('[name="relation-node"]:checked')].map(el=>({kind:'blueprint',id:el.value}));for(const [kind,id]of [['paragraph','relation-paragraph'],['decision','relation-decision']])for(const o of $('#'+id)?.selectedOptions||[])list.push({kind,id:o.value});return [...list,...existing.filter(t=>t.kind==='comment')]}
async function relationWrite(a){await flushSaves();if(syncBusy||Object.keys(pending).length)throw Error('请先完成当前保存或处理版本冲突');const id=currentId();a.projectId??=id;a.baseRevision??=versions[id];a.requestId??=crypto.randomUUID();$('#app').inert=true;let r;try{r=await api('/api/relations',a)}finally{$('#app').inert=false}versions[id]=r.project.revision;state=r.project.state;cacheProject();applyProjectSource();syncStatus();return r}
function relationSubmit(form,make){let attempt=null,signature='';form.onsubmit=async e=>{e.preventDefault();const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{const input=make(),nextSignature=JSON.stringify(input);if(nextSignature!==signature){attempt=input;signature=nextSignature}await relationWrite(attempt);$('#modal').close();page='relations';shell();toast('已保存到续章')}catch(err){$('#relation-error').textContent=err.message}finally{buttons.forEach(b=>b.disabled=false)}}}
const relationFooter=()=>`<p id="relation-error" role="alert"></p><div class="actions">${btn('取消','close')}<button type="submit" class="primary">保存</button></div>`;
function decisionForm(prior){const k=state.knowledge.find(k=>k.id===prior);$('#modal').innerHTML=`<h2>${k?'提出替代决定':'记录一个决定'}</h2>${k?`<div class="quote">原决定：${esc(k.title)}<br>${esc(k.body)}</div>`:''}<form id="relation-form"><label>新决定标题<input id="decision-title" required maxlength="200"></label><label>具体内容<textarea id="decision-body" required></textarea></label><label>为什么这样决定<textarea id="decision-reason" required></textarea></label><label>来源 / 哪次讨论<input id="decision-source" required placeholder="例如：本次与你讨论后确定的表达原则"></label><label>适用范围<input id="decision-scope" value="${esc(k?.scope||'')}"></label>${targetFields(k?.targets||[])}${relationFooter()}</form>`;$('#modal').showModal();relationSubmit($('#relation-form'),()=>({action:'decision',title:$('#decision-title').value,content:$('#decision-body').value,reason:$('#decision-reason').value,source:$('#decision-source').value,scope:$('#decision-scope').value,supersedes:prior,targets:readTargets(k?.targets)}))}
async function evidenceForm(id,draft){try{await refreshAssets()}catch{}const e=(state.evidence||[]).find(e=>e.id===id);const first=draft?.segments?.[0]?.block;$('#modal').innerHTML=`<h2>${e?'核对证据位置':'定位一条证据'}</h2><form id="relation-form"><label>证据标题<input id="evidence-title" required value="${esc(e?.title||'')}"></label><label for="evidence-source">来源段落或已导入文件</label><select id="evidence-source"><optgroup label="正文段落">${PAPER.paragraphs.filter(p=>p.text).map(p=>`<option value="paragraph:${esc(p.id)}" ${(e?.sourceType==='paragraph'&&e.sourceId===p.id)||first===p.id?'selected':''}>${esc(p.id+' · '+p.text.slice(0,65))}</option>`).join('')}</optgroup><optgroup label="已导入文件">${assetList.map(a=>`<option value="asset:${esc(a.id)}" ${e?.sourceType==='asset'&&e.sourceId===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</optgroup></select><details open><summary>当前来源文字（文件请下载核对）</summary><p id="evidence-preview" class="quote"></p></details><label>具体位置<input id="evidence-locator" required placeholder="段落、PDF第8页、表2，或工作表与单元格范围" value="${esc(e?.locator||first||'')}"></label><label>摘录 / 关键数值<textarea id="evidence-quote" required>${esc(e?.quote||draft?.quote||'')}</textarea></label><label>支持哪个判断<textarea id="evidence-purpose" required>${esc(e?.purpose||'')}</textarea></label>${targetFields(e?.targets||[])}${relationFooter()}</form>`;$('#modal').showModal();const preview=()=>{const [type,id]=$('#evidence-source').value.split(':');$('#evidence-preview').textContent=type==='paragraph'?P[id]?.text||'找不到段落':'文件位置由你登记；本工具尚未解析或验证文件内容。';};$('#evidence-source').onchange=preview;preview();relationSubmit($('#relation-form'),()=>{const [sourceType,sourceId]=$('#evidence-source').value.split(':');return {action:'evidence',id:e?.id,title:$('#evidence-title').value,sourceType,sourceId,locator:$('#evidence-locator').value,quote:$('#evidence-quote').value,purpose:$('#evidence-purpose').value,targets:readTargets(e?.targets)}})}
function relatedEvidence(node){const es=(state.evidence||[]).filter(e=>e.targets.some(t=>t.kind==='blueprint'&&t.id===node));return `<section class="bp-source"><h3>已定位证据 · ${es.length}</h3>${es.map(e=>`<p><strong>${esc(e.title)}</strong><br>${esc(e.locator)} · ${esc(localEvidenceStatus(e))}</p>`).join('')}${btn('管理证据与影响','relation-tab','data-tab="evidence"')}</section>`}
document.addEventListener('click',async ev=>{const b=ev.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;
 if(a==='relation-tab'){relationTab=b.dataset.tab;page='relations';shell()}
 if(a==='decision-form')decisionForm(b.dataset.prior);
 if(a==='evidence-form')await evidenceForm(b.dataset.id);
 if(a==='evidence-selection'){if(!selection){toast('请先选择一段正文');return}await evidenceForm(null,selection)}
 if(a==='decision-adopt'){const k=state.knowledge.find(k=>k.id===b.dataset.id);$('#modal').innerHTML=`<h2>采用这个决定</h2><h3>${esc(k.title)}</h3><p>${esc(k.body)}</p><p>理由：${esc(k.reason)}</p>${k.supersedes?`<div class="quote">将替代：${esc(state.knowledge.find(n=>n.id===k.supersedes)?.body)}</div>`:''}<p>关联位置会收到检查提醒，正文不会自动重写。</p><form id="relation-form">${relationFooter()}</form>`;$('#modal').showModal();$('#relation-form button[type="submit"]').textContent=k.supersedes?'采用并替代旧决定':'采用这个决定';relationSubmit($('#relation-form'),()=>({action:'adopt',id:k.id}))}
 if(a==='impact-review'){const i=state.impacts.find(i=>i.id===b.dataset.id);$('#modal').innerHTML=`<h2>记录检查结果</h2><p>${esc(i.reason)}</p><form id="relation-form"><label>检查结果与处理说明<textarea id="impact-note" required placeholder="例如：已对照新决定检查，本段表达仍适用；或说明具体修改">${esc(i.note||'')}</textarea></label>${relationFooter()}</form>`;$('#modal').showModal();$('#relation-form button[type="submit"]').textContent='确认已检查';relationSubmit($('#relation-form'),()=>({action:'review-impact',id:i.id,note:$('#impact-note').value}))}
});
