(()=>{'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='xuzhang-public-__INSTANCE__', P=Object.fromEntries(PAPER.paragraphs.map(p=>[p.id,p]));
const seed=[{id:'K1',kind:'写作原则',title:'保留依据与边界',body:'区分事实、推断和待核查问题；AI修改由作者检查。',source:'通用示例',anchor:'',status:'待核对'}];
let state={comments:[],overrides:{},colors:[],knowledge:seed,events:[]},page='blueprint',selected='',selection=null,composer=false,side='comments',filter='全部',kfilter='全部';
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&Array.isArray(saved.knowledge))state=saved}catch(e){}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',3200)}
function save(message){state.events.unshift({time:new Date().toLocaleString('zh-CN'),text:message});cacheProject();queueSave();}

const allComments=()=>[...PAPER.comments,...state.comments].map(c=>({...c,...state.overrides[c.id]}));
const statusName=s=>({imported:'导入待核对',todo:'待处理',review:'待你检查',done:'已确认'}[s]||s);
const btn=(text,action,extra='')=>`<button type="button" data-action="${action}" ${extra}>${text}</button>`;
function shell(){ $('#app').innerHTML=`<aside class="nav"><div class="brand">续章<small>让每次讨论都有下文</small></div><div class="project"><small>当前项目 / 论文</small><h3 style="margin:9px 0">续章入门示例</h3><span class="tag green">通用示例 · 可新建项目</span></div><nav>${[['blueprint','◇','创作蓝图'],['paper','▱','论文思路与规则'],['discussions','◉','讨论成果'],['review','▤','作品预览'],['changes','⇄','修改对照'],['overview','◫','项目概览'],['comments','◷','批注与进度'],['assets','▣','素材与文件'],['knowledge','▧','资料与依据'],['relations','◎','决定、证据与影响'],['history','↺','变更记录']].map(([id,ic,n])=>btn(`${ic}　${n}`,'nav',`data-page="${id}" class="${page===id?'active':''}"`)).join('')}</nav><div class="bottom"><strong>Codex 连接</strong><span id="codex-connection">正在检查本机连接</span><br>继续在原来的对话框工作</div></aside><div class="main"><header><span>续章入门示例 <span class="muted"> / 项目工作台</span></span><div class="actions">${btn('接续资料','handoff')}${btn('导出记录','export')}</div></header><div class="notice"><span>本机保存 · 通过初始化导入建立自己的项目</span><span id="save-status">正在连接项目数据库</span></div><main id="content"></main></div>`;renderContent();projectControls();syncStatus();connectionStatus()}
function head(title,sub,extra=''){return `<div class="pagehead"><div><div class="section-label">PAPER WORKSPACE</div><h1>${title}</h1><small>${sub}</small></div>${extra}</div>`}
function rich(p){const cuts=new Set([0,p.text.length]);p.runs.forEach(r=>{cuts.add(r.start);cuts.add(r.end)});const cs=allComments().flatMap(c=>c.segments.filter(s=>s.block===p.id).map(s=>({...s,id:c.id})));const colors=state.colors.filter(c=>c.block===p.id);[...cs,...colors].forEach(s=>{cuts.add(s.start);cuts.add(s.end)});const points=[...cuts].sort((a,b)=>a-b);return points.slice(0,-1).map((a,i)=>{let b=points[i+1],r=p.runs.find(r=>r.start<=a&&r.end>a)||{},c=colors.filter(c=>c.start<=a&&c.end>=b).at(-1),style=`${r.bold?'font-weight:bold;':''}${r.italic?'font-style:italic;':''}${r.vertical==='superscript'?'vertical-align:super;font-size:smaller;':r.vertical==='subscript'?'vertical-align:sub;font-size:smaller;':''}`;let color=c?(c.color||r.color):r.color;if(color&&/^[a-f\d]{6}$/i.test(color))style+='color:#'+color+';';let text=`<span style="${style}">${esc(p.text.slice(a,b))}</span>`,marks=cs.filter(s=>s.start<=a&&s.end>=b);return marks.length?`<mark data-comment="${marks[0].id}" class="${marks.some(m=>m.id===selected)?'focused':''}">${text}</mark>`:text}).join('')}
function paragraph(p){p=P[p.id]||p;const cs=allComments().filter(c=>c.segments.some(s=>s.block===p.id));return `<section class="para ${p.type}" id="${p.id}">${p.maths.length?`<div class="formula">${p.maths.map(m=>m.mathml).join('')}${esc(p.text.slice(p.maths.at(-1).end))}</div><details class="formula-source"><summary>公式原始文字 · 可选取批注</summary><div class="rich-text" data-pid="${p.id}">${rich(p)}</div></details>`:`<div class="rich-text" data-pid="${p.id}">${rich(p)}</div>`}${p.images.map(k=>`<img loading="lazy" width="${PAPER.images[k].width}" height="${PAPER.images[k].height}" src="${PAPER.images[k].data}" alt="原稿内嵌图片，位置${p.id}">`).join('')}${cs.length?`<button class="comment-pin" aria-label="查看此段${cs.length}条批注" data-action="comment" data-id="${cs[0].id}">${cs.length}</button>`:''}</section>`}
function article(){return PAPER.blocks.map(b=>b.type==='table'?`<div class="table-wrap"><table><tbody>${b.rows.map(row=>`<tr>${row.map(cell=>`<td colspan="${cell.colspan}">${cell.blocks.map(paragraph).join('')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:paragraph(b)).join('')}
function renderContent(){let html='';if(page==='discussions'){html=discussionView()}else if(page==='paper'){html=paperView()}else if(page==='relations'){html=relationsView()}else if(page==='assets'){html=assetsView()}else if(page==='blueprint'){html=blueprintView()}else if(page==='changes'){html=blueprintChanges()}else if(page==='review'){html=head('作品预览','选中文字，添加批注或改变文字颜色。原稿与修改意见放在一起。',`<span class="tag">${state.manuscript?.changes?.length?'当前工作草稿':state.project?'初始化导入草稿':'入门示例'}</span>`)+`<div class="toolbar"><select id="outline" aria-label="跳转章节"><option value="">文章目录</option>${PAPER.outline.map(o=>`<option value="${o.id}">${'　'.repeat(o.level-1)}${esc(o.title)}</option>`).join('')}</select><span class="sep"></span>${btn('＋ 批注','annotate','class="primary"')}${[['B5463C','红色'],['346CBD','蓝色'],['258567','绿色'],['273349','黑色']].map(([v,n])=>`<button class="color" style="--ink:#${v};color:#${v}" data-action="color" data-color="${v}" aria-label="文字${n}" title="文字${n}">A</button>`).join('')}${btn('原色','color','data-color=""')}${btn('存入写作依据','capture')}${btn('定位为证据','evidence-selection')}<span id="selection-hint" class="selected-hint">拖动选择正文文字</span></div><div class="review-grid"><article class="paper"><div class="paper-meta"><span>审阅副本 / 全文连续阅读</span><span>${PAPER.counts.comments} 条原批注 · ${PAPER.counts.tables} 张表 · ${PAPER.counts.images} 张图片</span></div><details style="margin-bottom:24px;font-size:12px;color:#748194"><summary>来源与版本说明</summary><p>${esc(PAPER.source)}</p><p>${state.project?'这里展示当前工作草稿；原始导入内容与后续修改记录均保留。':'这是软件自带的通用示例；请通过初始化导入建立自己的项目。'}</p></details>${article()}</article><aside class="sidepanel" id="sidepanel"></aside></div>`}
else if(page==='overview'){let cs=allComments(),done=cs.filter(c=>c.status==='done').length;html=head('让论文的来路与下一步都清楚','从一条意见开始，把理由沉淀为写作依据。')+`<div class="metrics">${[['全文段落',PAPER.counts.nonemptyParagraphs],['原Word批注',PAPER.comments.length],['已确认批注',done],['写作依据',state.knowledge.length]].map(([n,v])=>`<div class="metric"><small>${n}</small><b>${v}</b></div>`).join('')}</div><div class="cards"><section class="card"><h2>${state.project?esc(state.project.name):'开始你的第一个项目'}</h2><p>${state.project?esc(state.blueprint.goal):'从初始化导入开始，保存目标、草稿和待核查事项。'}</p>${state.project?btn('继续编辑创作蓝图','nav','data-page="blueprint" class="primary"'):btn('新建项目','init-open','class="primary"')}</section><section class="card"><h2>检查进度</h2><p>${cs.length} 条批注中，${done} 条由你在本页面明确确认。</p><div class="progress"><span style="width:${cs.length?done/cs.length*100:0}%"></span></div><small>导入的历史批注统一待核对，历史AI回复不自动计为完成。</small></section></div>`}
else if(page==='comments'){let cs=allComments().filter(c=>filter==='全部'||c.status===filter);html=head('批注与修改进度','保留原话、原文位置和回复历史。已修改与已确认分别记录。')+`<div class="filters">${[['全部','全部'],['imported','导入待核对'],['todo','待处理'],['review','待你检查'],['done','已确认']].map(([v,n])=>btn(n,'filter',`data-value="${v}" class="${filter===v?'active':''}"`)).join('')}</div><div class="cards">${cs.map(c=>`<section class="card"><span class="tag">${esc(c.id)} · ${statusName(c.status)}</span><h3 style="margin-top:12px">${esc(c.text.split('\n')[0])}</h3>${c.anchorNeedsReview?'<p class="tag amber">原文已改，选区需核对；此批注暂关联到段落，以下保留原引用。</p>':''}<div class="quote">${esc(c.quote)}</div><small>${esc(c.author||'我')} · ${c.id.startsWith('W-')?'原Word批注':'网页新增'}</small><div class="actions">${btn('定位并查看','comment',`data-id="${c.id}"`)}</div></section>`).join('')||'<p class="empty">这个状态下还没有批注</p>'}</div>`}
else if(page==='knowledge'){html=head('写作依据','积累目标、论证思路、写作原则和证据位置。每条保留来源，随讨论更新。',btn('＋ 新增依据','new-knowledge','class="primary"'))+`<div class="filters">${['全部','目标','论证思路','写作原则','证据位置'].map(k=>btn(k,'kfilter',`data-value="${k}" class="${kfilter===k?'active':''}"`)).join('')}</div><div class="cards">${state.knowledge.filter(k=>k.lifecycle!=='superseded').filter(k=>kfilter==='全部'||k.kind===kfilter).map(k=>`<section class="card"><div class="actions"><span class="tag green">${k.kind}</span><span class="tag ${k.status==='待核对'?'amber':''}">${esc(k.status)}</span></div><h2 style="margin-top:14px">${esc(k.title)}</h2><p>${esc(k.body)}</p><div class="source">来源 / ${esc(k.source)}</div><div class="actions">${k.anchor?btn('查看关联原文','jump',`data-id="${k.anchor}"`):''}${btn('编辑','edit-knowledge',`data-id="${k.id}"`)}</div></section>`).join('')}</div>`}
else{html=head('变更记录','本页面的操作记录；原稿中的历史回复保留在各条批注内。')+`<div class="timeline">${state.events.map(e=>`<div class="event"><small>${esc(e.time)}</small><div>${esc(e.text)}</div></div>`).join('')||'<div class="empty">还没有本地操作记录</div>'}</div>`}$('#content').innerHTML=html;if(page==='review')panel();if(page==='blueprint')liveBlueprint()}
function panel(){if(!$('#sidepanel'))return;const c=allComments().find(c=>c.id===selected);$('#sidepanel').innerHTML=`<div class="panel-tabs">${btn('批注','side','data-tab="comments" class="'+(side==='comments'?'active':'')+'"')}${btn('写作依据','side','data-tab="knowledge" class="'+(side==='knowledge'?'active':'')+'"')}</div><div class="panelbody">${composer?`<span class="tag green">新批注</span><h3 style="margin-top:12px">对这段文字说点什么</h3><div class="quote">${esc(selection?.quote)}</div><form id="comment-form"><label for="comment-input">你的修改意见</label><textarea id="comment-input" required placeholder="哪里需要改？希望怎么改？"></textarea><div class="actions"> <button class="primary" type="submit">保存批注</button>${btn('取消','cancel')}</div></form>`:side==='knowledge'?`<h3>与这篇论文一起积累</h3><small>选中文字可直接存入依据。</small>${state.knowledge.filter(k=>k.lifecycle!=='superseded').filter(k=>!c||!k.anchor||c.segments.some(s=>s.block===k.anchor)||k.kind==='目标'||k.kind==='论证思路').map(k=>`<button class="case" data-action="edit-knowledge" data-id="${k.id}"><span class="tag">${k.kind} · ${k.status}</span><strong>${esc(k.title)}</strong><small>${esc(k.body.slice(0,90))}…</small></button>`).join('')}${btn('查看全部写作依据','nav','data-page="knowledge"')}`:`<div class="section-label">批注与回复</div>${c?`<div class="linked"><div class="actions"><span class="tag amber">${statusName(c.status)}</span><small>${esc(c.id)} · ${esc(c.author||'我')}</small></div>${c.anchorNeedsReview?'<p class="tag amber">原文已改，选区需核对；此批注暂关联到段落，以下保留原引用。</p>':''}<div class="quote">${esc(c.quote)}</div>${btn('定位原文','jump',`data-id="${c.segments[0].block}"`)}${linkedBlueprint(c)}<h3 style="margin-top:20px">${c.id.startsWith('W-')?'原批注与回复历史':'修改意见'}</h3><div class="history-text">${esc(c.text)}</div>${(c.replies||[]).map(r=>`<div class="reply"><small>${esc(r.time)} · 本页追加</small><div>${esc(r.text)}</div></div>`).join('')}<form id="reply-form"><label for="reply">继续记录</label><textarea id="reply" required placeholder="补充意见或记录处理说明"></textarea><button type="submit">保存补充</button></form><label for="status">当前处理状态</label><select id="status">${['imported','todo','review','done'].map(v=>`<option value="${v}" ${c.status===v?'selected':''}>${statusName(v)}</option>`).join('')}</select><p class="muted" style="margin-top:10px">状态由你明确更改。此页尚未接入AI自动修改。</p></div>`:''}`}</div>`;layoutComments()}
function layoutComments(){
 const rail=$('#sidepanel');if(!rail)return;
 const detail=rail.innerHTML;const current=allComments().find(c=>c.id===selected);
 const entries=allComments().map(c=>({id:c.id,block:c.segments[0].block,c}));
 if(composer&&selection)entries.push({id:'draft',block:selection.segments[0].block});
 entries.sort((a,b)=>PAPER.paragraphs.findIndex(p=>p.id===a.block)-PAPER.paragraphs.findIndex(p=>p.id===b.block));
 rail.innerHTML=entries.map(e=>`<div class="rail-card ${e.id===selected?'is-selected':''}" data-rail="${e.id}" data-block="${e.block}">${(composer?e.id==='draft':e.id===selected)?detail:`<button class="rail-open" data-action="comment" data-id="${e.id}"><span class="tag">${esc(e.id)} · ${statusName(e.c.status)}${e.c.anchorNeedsReview?' · 选区需核对':''}</span><strong>${esc(e.c.text.split('\n')[0])}</strong><small>${esc(e.c.author||'我')} · 点击展开回复与处理</small></button>`}</div>`).join('')+'<svg class="comment-lines" aria-hidden="true"></svg>';
 alignComments();
}
function alignComments(){
 const rail=$('#sidepanel');if(!rail)return;const rr=rail.getBoundingClientRect();let bottom=0,lines=[];
 rail.querySelectorAll('.rail-card').forEach(card=>{const p=document.getElementById(card.dataset.block);if(!p)return;const pr=p.getBoundingClientRect(),anchor=Math.max(0,(p.querySelector(`[data-comment="${card.dataset.rail}"]`)?.getClientRects()[0]?.top??pr.top)-rr.top+12),y=Math.max(anchor-15,bottom);card.style.top=y+'px';const x=pr.right-rr.left;lines.push(`<path d="M ${x} ${anchor} H -12 V ${y+24} H 0"/>`);bottom=y+card.offsetHeight+16});
 rail.style.height=Math.max(bottom,document.querySelector('.paper').offsetHeight)+'px';const svg=rail.querySelector('svg');svg.innerHTML=lines.join('');svg.setAttribute('viewBox',`-60 0 60 ${Math.max(bottom,document.querySelector('.paper').offsetHeight)}`);svg.style.height=rail.style.height;
}
window.addEventListener('resize',()=>requestAnimationFrame(alignComments));
function captureSelection(){const s=window.getSelection();if(!s||s.isCollapsed||!s.rangeCount)return;const range=s.getRangeAt(0),segments=[];document.querySelectorAll('.rich-text').forEach(el=>{if(!range.intersectsNode(el))return;const r=range.cloneRange();if(!el.contains(r.startContainer))r.setStart(el,0);if(!el.contains(r.endContainer))r.setEnd(el,el.childNodes.length);const pre=document.createRange();pre.selectNodeContents(el);pre.setEnd(r.startContainer,r.startOffset);const start=pre.toString().length,end=start+r.toString().length;if(end>start)segments.push({block:el.dataset.pid,start,end})});if(segments.length){selection={segments,quote:segments.map(s=>P[s.block].text.slice(s.start,s.end)).join('\n')};if($('#selection-hint'))$('#selection-hint').textContent='已选 '+selection.quote.length+' 字 · '+segments.length+' 段'}}
function jump(id){const related=allComments().find(c=>c.segments.some(s=>s.block===id));if(related&&!allComments().find(c=>c.id===selected)?.segments.some(s=>s.block===id))selected=related.id;composer=false;if(page!=='review'){page='review';shell()}requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({block:'center',behavior:'instant'}))}
function editKnowledge(id,draft){if(state.knowledge.find(k=>k.id===id)?.lifecycle){page='relations';shell();return}const k=state.knowledge.find(k=>k.id===id)||{id:'K'+Date.now(),kind:'证据位置',title:'',body:draft?.quote||'',source:draft?'选自指定稿 '+draft.segments.map(s=>s.block).join('、'):'',anchor:draft?.segments[0].block||'',status:'待核对'};const d=$('#modal');d.innerHTML=`<h2>${id?'编辑写作依据':'新增写作依据'}</h2><form id="knowledge-form"><label for="kind">类别</label><select id="kind">${['目标','论证思路','写作原则','证据位置'].map(n=>`<option ${n===k.kind?'selected':''}>${n}</option>`).join('')}</select><label for="ktitle">标题</label><input id="ktitle" required value="${esc(k.title)}"><label for="kbody">内容 / 理由</label><textarea id="kbody" required>${esc(k.body)}</textarea><label for="ksource">来源或文件位置</label><textarea id="ksource" style="min-height:65px">${esc(k.source)}</textarea><label for="kstatus">核对状态</label><select id="kstatus">${['待核对','来源原话','已确认'].map(n=>`<option ${n===k.status?'selected':''}>${n}</option>`).join('')}</select><div class="actions">${btn('取消','close')}<button class="primary" type="submit">保存依据</button></div></form>`;d.showModal();$('#knowledge-form').onsubmit=e=>{e.preventDefault();if(!$('#ktitle').value.trim()||!$('#kbody').value.trim())return;const n={...k,kind:$('#kind').value,title:$('#ktitle').value.trim(),body:$('#kbody').value.trim(),source:$('#ksource').value.trim(),status:$('#kstatus').value};const i=state.knowledge.findIndex(v=>v.id===k.id);if(i<0)state.knowledge.push(n);else state.knowledge[i]=n;save('保存写作依据：'+n.title);d.close();if(page==='knowledge')renderContent();else panel();toast('写作依据已保存')}}
function handoff(){const cs=allComments();$('#modal').innerHTML=`<h2>接续资料</h2><p class="muted">把当前写作依据和未完成意见带入下一次讨论。Codex 可通过 xuzhang 工具读取；以下也可复制留存。</p><textarea style="height:380px" readonly>${esc('# '+PAPER.title+'\n来源：'+PAPER.source+'\n版本：'+PAPER.sha256+'\n\n'+'## 创作蓝图\n作品目标：'+state.blueprint.goal+'\n'+state.blueprint.nodes.map(n=>'### '+n.title+'\n'+bpFields.filter(f=>f[0]!=='title').map(([k,label])=>label+'：'+n[k]).join('\n')+'\n关联批注：'+n.comments.join('、')).join('\n\n')+'\n\n'+state.knowledge.map(k=>'## '+k.kind+' / '+k.title+' ['+decisionLabel(k)+']\n'+k.body+'\n来源：'+k.source).join('\n\n')+'\n\n## 证据定位\n'+(state.evidence||[]).map(e=>e.title+'：'+e.locator+'；'+e.quote+'；支撑：'+e.purpose).join('\n')+'\n\n## 待检查影响\n'+(state.impacts||[]).filter(i=>i.status!=='resolved').map(i=>i.title+'：'+i.reason).join('\n')+'\n\n## 未完成批注\n'+cs.filter(c=>c.status!=='done').map(c=>c.id+' ['+statusName(c.status)+'] '+c.text+'\n原文：'+c.quote).join('\n\n')+discussionHandoff())}</textarea><div class="actions">${btn('关闭','close')}</div>`;$('#modal').showModal()}
document.addEventListener('mouseup',captureSelection);document.addEventListener('keyup',e=>{if(e.key==='Shift'||e.key.startsWith('Arrow'))captureSelection()});document.addEventListener('pointerdown',e=>{if(e.target.closest('.toolbar button')){captureSelection();e.preventDefault()}});
document.addEventListener('click',e=>{const mark=e.target.closest('[data-comment]');if(mark){selected=mark.dataset.comment;composer=false;side='comments';panel();return}const b=e.target.closest('[data-action]');if(!b)return;let a=b.dataset.action;if(a==='nav'){page=b.dataset.page;composer=false;shell();window.scrollTo(0,0)}else if(a==='comment'){selected=b.dataset.id;composer=false;side='comments';if(page!=='review'){page='review';shell();jump(allComments().find(c=>c.id===selected).segments[0].block)}else panel()}else if(a==='jump')jump(b.dataset.id);else if(a==='side'){side=b.dataset.tab;composer=false;panel()}else if(a==='annotate'||a==='capture'||a==='color'){if(!selection){toast('请先在正文中选择文字');return}if(a==='annotate'){composer=true;side='comments';panel();$('#comment-input').focus();if(innerWidth<650)document.querySelector('[data-rail="draft"]')?.scrollIntoView({block:'center'})}else if(a==='capture')editKnowledge(null,selection);else{selection.segments.forEach(s=>state.colors.push({...s,color:b.dataset.color}));save('调整选中文字颜色：'+(b.dataset.color||'恢复原色'));selection.segments.forEach(s=>{const el=document.querySelector(`[data-pid="${s.block}"]`);if(el)el.innerHTML=rich(P[s.block])});window.getSelection().removeAllRanges();toast('颜色调整已记录，保存结果见顶部')}}else if(a==='cancel'){composer=false;panel()}else if(a==='filter'){filter=b.dataset.value;renderContent()}else if(a==='kfilter'){kfilter=b.dataset.value;renderContent()}else if(a==='new-knowledge')editKnowledge();else if(a==='edit-knowledge')editKnowledge(b.dataset.id);else if(a==='close')$('#modal').close();else if(a==='handoff')handoff();else if(a==='export'){const data={schema:'xuzhang-review-v2',source:PAPER.source,sha256:PAPER.sha256,exportedAt:new Date().toISOString(),originalComments:PAPER.comments,...state},url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='续章_论文审阅记录.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出批注、颜色、写作依据及操作记录')}});
document.addEventListener('change',e=>{if(e.target.id==='outline'&&e.target.value)jump(e.target.value);if(e.target.id==='status'){state.overrides[selected]={...state.overrides[selected],status:e.target.value};save('批注 '+selected+' → '+statusName(e.target.value));panel()}});
document.addEventListener('submit',e=>{if(e.target.id==='comment-form'){e.preventDefault();const text=$('#comment-input').value.trim();if(!text)return;const c={id:'N-'+Date.now(),author:'我',date:new Date().toISOString(),text,quote:selection.quote,segments:structuredClone(selection.segments),status:'todo'};state.comments.push(c);selected=c.id;save('新增批注：'+text);composer=false;const y=scrollY;renderContent();window.scrollTo(0,y);toast('批注已记录并关联原文，保存结果见顶部')}else if(e.target.id==='reply-form'){e.preventDefault();const text=$('#reply').value.trim();if(!text)return;const c=allComments().find(c=>c.id===selected);state.overrides[selected]={...state.overrides[selected],replies:[...(c.replies||[]),{time:new Date().toLocaleString('zh-CN'),text}]};save('补充批注 '+selected);panel()}});
/* BLUEPRINT_EXTENSION */
/* CLAIMS_EXTENSION */
/* ASSET_SEARCH_EXTENSION */
/* DISCUSSION_EXTENSION */
/* PAPER_EXTENSION */
/* IMPORTS_EXTENSION */
/* RELATIONS_EXTENSION */
/* VERSION_EXTENSION */
/* PERSISTENCE_EXTENSION */
shell();
bootStorage();
})();
