'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {openStore}=require('./store'),rel=require('./relations'),{applyDraft}=require('./draft-edit');
const root=fs.mkdtempSync(path.join(__dirname,'验证数据/relations-'));
const store=openStore(root),id='p-8877665544332211';
const m={id,name:'决定与证据 · 隔离验证',root:path.join(root,id),input:{项目名称:'决定与证据 · 隔离验证',目标:'核对决定与证据的关联',内容:[{名称:'压力试验',草稿:'1.4 MPa下，正面与侧面保持低温，顶面出现回升。'},{名称:'结论',草稿:'优化应关注持续冷却和回升位置。'}]}};
fs.mkdirSync(path.join(m.root,'00_项目'),{recursive:true});fs.writeFileSync(path.join(m.root,'00_项目/项目.json'),JSON.stringify(m));store.addProject(m);
let serial=0;const get=()=>store.get(id),act=(a,actor='用户')=>{const r=get(),req={...a,requestId:a.requestId||'relations-test-'+(++serial)};return store.mutate(id,r.revision,req.requestId,req,s=>rel.perform(s,req,{source:rel.sourceFor(store,s),assets:store.assets(id),actor}))};
act({action:'decision',title:'按整体均温评价',content:'先看整体平均温度',source:'隔离测试',reason:'原有方案',scope:'压力系列',targets:[{kind:'blueprint',id:'I-0'}]});let prior=get().state.knowledge.at(-1).id;
act({action:'adopt',id:prior});
act({action:'decision',title:'按部位解释持续冷却',content:'比较顶面、正面和侧面的持续温度与回升过程。',source:'测试讨论',reason:'整体均温会掩盖局部差异',scope:'压力系列',supersedes:prior,targets:[{kind:'blueprint',id:'I-1'}]});const next=get().state.knowledge.at(-1).id;
assert.equal(get().state.knowledge.find(k=>k.id===prior).lifecycle,'active');
act({action:'decision',title:'另一候选',content:'另一个候选',source:'测试',reason:'并发候选测试',supersedes:prior,targets:[]});const competing=get().state.knowledge.at(-1).id;
assert.throws(()=>act({action:'adopt',id:next},'Codex'),/用户/);
act({action:'adopt',id:next});assert.equal(get().state.knowledge.find(k=>k.id===prior).supersededBy,next);assert.equal(get().state.knowledge.find(k=>k.id===next).targets.length,2);
assert.throws(()=>act({action:'adopt',id:competing}),/其他决定/);
assert.ok(get().state.impacts.some(i=>i.target.id==='import-0-0'));
const eArgs={action:'evidence',title:'分部位温度表现',sourceType:'paragraph',sourceId:'import-0-0',locator:'压力试验第一段',quote:'正面与侧面保持低温',purpose:'支撑分部位解释',targets:[{kind:'blueprint',id:'I-1'},{kind:'decision',id:next}]};
act(eArgs,'Codex');const eid=get().state.evidence[0].id;
assert.throws(()=>act({...eArgs,quote:'不存在的摘录'}),/摘录不在/);
assert.throws(()=>act({...eArgs,targets:[{kind:'blueprint',id:'missing'}]}),/不存在/);
const before=get();const dr={baseRevision:before.revision,edits:[{paragraphId:'import-0-0',expectedText:m.input.内容[0].草稿,text:'当前草稿新增了持续冷却的解释。'}],commentIds:[],blueprintChangeIndices:[],reason:'测试来源变化'};
store.mutate(id,before.revision,'draft-relations-test',dr,s=>applyDraft(s,rel.sourceFor(store,s),dr));
let s=get().state;assert.match(rel.evidenceStatus(s.evidence[0],s,rel.sourceFor(store,s),[]),/变化/);assert.ok(s.impacts.some(i=>i.target.id===eid));assert.ok(s.impacts.some(i=>i.source.kind==='paragraph'&&i.target.id==='I-1'));
const alert=s.impacts.find(i=>i.target.id===eid);act({action:'review-impact',id:alert.id,note:'已检查，需要换用新摘录'},'Codex');assert.equal(get().state.impacts.find(i=>i.id===alert.id).status,'review');act({action:'review-impact',id:alert.id,note:'已核对来源变化，后续更新摘录'});assert.equal(get().state.impacts.find(i=>i.id===alert.id).status,'resolved');
act({...eArgs,id:eid,quote:'新增了持续冷却',purpose:'修订后的表达依据'},'Codex');assert.equal(get().state.evidence[0].history.length,1);
let r=get(),fake=structuredClone(r.state);fake.knowledge.find(k=>k.id===next).body='绕过历史改写';assert.throws(()=>store.save({id,baseRevision:r.revision,requestId:'forged-save',state:fake}),/决定/);
let state=structuredClone(r.state);state.blueprint.nodes[1].claim='新的结论';const job={id,baseRevision:r.revision,requestId:'normal-save',state};const saved=store.save(job);assert.deepEqual(store.save(job),saved);assert.throws(()=>store.save({...job,requestId:'stale-save'}),/更新版本/);assert.ok(saved.impacts.length);
const asset={id:'a-0011223344556677',project:id,name:'测试表格.csv',path:path.join(root,'测试表格.csv'),sha256:'original-hash'};fs.writeFileSync(asset.path,'工况,结果\n测试,1');store.addAsset(asset);
act({action:'evidence',title:'表格证据',sourceType:'asset',sourceId:asset.id,locator:'工作表1 A1:B2',quote:'测试,1',purpose:'记录原文件的具体区域',targets:[{kind:'blueprint',id:'I-0'}]},'Codex');
const fileEvidence=get().state.evidence.at(-1);assert.equal(fileEvidence.sourceHash,asset.sha256);assert.match(rel.evidenceStatus(fileEvidence,get().state,rel.sourceFor(store,get().state),[{...asset,sha256:'new-hash'}]),/变化/);
assert.throws(()=>act({action:'evidence',title:'非法来源',sourceType:'asset',sourceId:'missing',locator:'第1页',quote:'内容',purpose:'测试',targets:[{kind:'blueprint',id:'I-0'}]}),/导入/);
assert.equal(store.db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');store.close();const again=openStore(root);assert.equal(again.get(id).state.evidence[0].history.length,1);again.close();
fs.writeFileSync(path.join(__dirname,'验证数据/relations-latest.json'),JSON.stringify({root,id},null,2));
console.log('PASS: candidate/adoption/replacement chain, competing proposals, target inheritance, exact quote validation, stale evidence, transitive/cyclic impact traversal, review states, history, replay/conflict, restart, integrity');console.log(root);
