const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {openStore}=require('./store'),rel=require('./relations'),claims=require('./claims'),review=require('./discussion-review'),{applyDraft}=require('./draft-edit');
const root=fs.mkdtempSync(path.join(__dirname,'验证数据/claims-review-')),store=openStore(root),pid='p-abcdef0011223344';const m={id:pid,name:'主张与验收隔离验证',root:path.join(root,pid),input:{项目名称:'主张与验收隔离验证',目标:'检验主张证据关联',内容:[{名称:'结果',核心表达:'候选分论点',草稿:'压力记录为0.4 MPa。'},{名称:'讨论',草稿:'适用范围尚待核查。'}]}};store.addProject(m);fs.mkdirSync(path.join(m.root,'00_项目'),{recursive:true});fs.writeFileSync(path.join(m.root,'00_项目/项目.json'),JSON.stringify(m));let serial=0;
const get=()=>store.get(pid),change=fn=>{const r=get();return store.mutate(pid,r.revision,'test-'+(++serial),{test:serial},s=>fn(s,r.revision))};
const evidence={action:'evidence',title:'压力记录',sourceType:'paragraph',sourceId:'import-0-0',locator:'结果第1段',quote:'0.4 MPa',purpose:'核对实验条件',targets:[{kind:'blueprint',id:'I-0'}],requestId:'evidence-1'};
change(s=>rel.perform(s,evidence,{source:rel.sourceFor(store,s),assets:[],actor:'用户'}));const eid=get().state.evidence[0].id;
change(s=>claims.update(s,{id:'I-0',support:[eid],counter:[],conditions:'当前实验条件',boundary:'不能推广到其他压力',nodes:['I-0'],paragraphs:['import-1-0'],reason:'关联结果与讨论',reviewed:true,reviewNote:'核对了摘录和条件'},rel.sourceFor(store,s),'用户'));
let r=get();assert.equal(claims.inspect(r.state,rel.sourceFor(store,r.state),[])[0].reviewComplete,true);
assert.throws(()=>change(s=>claims.update(s,{id:'I-0',support:['missing'],counter:[],nodes:[],paragraphs:[],conditions:'',boundary:'',reason:'失败'},rel.sourceFor(store,s))),/证据编号不存在/);
change(s=>rel.perform(s,{...evidence,id:eid,purpose:'还需核查压力测量位置'}, {source:rel.sourceFor(store,s),assets:[],actor:'用户'}));r=get();assert.equal(claims.inspect(r.state,rel.sourceFor(store,r.state),[])[0].reviewComplete,false);for(const kind of ['claim','blueprint','paragraph'])assert.ok(r.state.impacts.some(i=>i.target.kind===kind));
const discussion='T-restore-test';change((s,base)=>{s.blueprint.nodes[0].claim='改后的候选分论点';applyDraft(s,rel.sourceFor(store,s),{baseRevision:base,edits:[{paragraphId:'import-0-0',expectedText:'压力记录为0.4 MPa。',text:'压力记录为0.4 MPa，仍需核查。'}],commentIds:[],blueprintChangeIndices:[],reason:'隔离改稿'});s.discussions=[{id:discussion,title:'解释压力条件',goal:'试验恢复',summary:'先核查再下结论',reason:'测试',time:new Date().toISOString(),actor:'Codex',revision:base+1,operations:[{operation:'submit_draft',reason:'核查边界'}],changes:{paperIndices:[],blueprintIndices:[],manuscriptIndices:[0]},openQuestions:['测量位置待核查'],nextSteps:['查看原始记录']}];});const submitted=get();
const action=(type,id=discussion,note='隔离核查')=>review.perform(store,{projectId:pid,discussionId:id,baseRevision:get().revision,requestId:'review-'+(++serial),action:type,note});
action('needs_changes');assert.equal(review.info(store,pid,discussion).status,'needs_changes');action('accepted');assert.equal(review.info(store,pid,discussion).status,'accepted');
change(s=>s.blueprint.nodes[1].claim='后续无关章节修改必须保留');const beforeRestore=get();action('restored');r=get();assert.equal(r.revision,beforeRestore.revision+1);assert.equal(r.state.blueprint.nodes[0].claim,'候选分论点');assert.equal(r.state.blueprint.nodes[1].claim,'后续无关章节修改必须保留');assert.equal(r.state.manuscript.edits['import-0-0'],undefined);assert.equal(r.state.discussions[0].id,discussion);assert.equal(r.state.manuscript.changes.length,2);assert.equal(r.state.discussionReviews.length,3);
// A later edit to a touched entity blocks the entire restore, including unrelated fields in that group.
change((s,base)=>{s.blueprint.nodes[0].claim='第二次调整';s.discussions.push({...submitted.state.discussions[0],id:'T-conflict',title:'后续修改冲突验证',revision:base+1})});change(s=>s.blueprint.nodes[0].claim='用户后续改动');const unchanged=JSON.stringify(get());assert.throws(()=>action('restored','T-conflict'),/后续修改/);assert.equal(JSON.stringify(get()),unchanged);
// An unsubmitted chapter draft also prevents restoration.
change((s,base)=>{s.blueprint.nodes[1].claim='第三次调整';s.discussions.push({...submitted.state.discussions[0],id:'T-draft',title:'未提交草稿保护',revision:base+1})});change(s=>s.blueprint.drafts['I-1']={...s.blueprint.nodes[1],claim:'尚未提交'});assert.throws(()=>action('restored','T-draft'),/未提交草稿/);
const state=get().state;state.discussionReviews=[];assert.throws(()=>store.save({id:pid,baseRevision:get().revision,requestId:'reject-erase',state}),/专用操作/);assert.equal(store.db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');store.close();console.log('PASS: claim evidence links, validation, recheck invalidation, propagated reminders; accept/return/restore, preserved history/unrelated edits, conflict and draft guards');console.log(root);
