let versionView=null,versionRows=[],versionCursor=null,versionTab='text',versionMarks=true,versionRequest=0;
const versionLabels={claim:'主张',question:'问题',goal:'目标',evidence:'依据',reasoning:'推理',logic:'推理',expression:'表达',title:'标题',body:'内容',text:'文字',status:'状态',summary:'摘要',openQuestions:'未决问题',nextSteps:'下一步',boundary:'边界',argument:'论证思路',facts:'事实',terms:'术语',allocation:'章节安排',part:'章节',source:'来源',replies:'回复',reason:'原因',actor:'修改者',time:'时间',revision:'版本'};
function versionValue(v){if(v===null||v===undefined)return '（无）';if(typeof v!=='object')return String(v);if(Array.isArray(v))return v.map(versionValue).join('\n');return Object.entries(v).filter(([k])=>!['id','segments','anchorHistory','operations','input'].includes(k)).map(([k,x])=>(versionLabels[k]||k)+'：'+versionValue(x)).join('\n')}
function versionDetailHtml(){const v=versionView;if(!v)return '';const counts=Object.entries(v.counts).map(([area,n])=>`${area} ${n} 项`).join(' · ')||'没有内容变化';
 const summary=`<div class="version-summary"><h3>${esc(v.title)}</h3><p>版本 ${v.baseRevision} → ${v.revision} · ${esc(new Date(v.time).toLocaleString())}</p><p>${esc(counts)}</p><p class="muted">当前为只读查看，切换阶段不会覆盖最新内容。接受或恢复成果仍在“讨论成果”中操作。</p></div>`;
 const tabs=`<div class="actions">${[['text','阶段正文'],['ideas','思路与蓝图'],['diff','改动明细']].map(([key,label])=>btn(label,'version-tab',`data-tab="${key}" class="${versionTab===key?'primary':''}"`)).join('')}${btn(versionMarks?'隐藏修改标记':'显示修改标记','version-marks')}</div>`;
 let content='';if(versionTab==='text'){content=`<p class="muted">${versionMarks?'红色仅表示本次比较新增或改写的文字；删减及前后全文见“改动明细”。':'修改标记已隐藏，正文和历史记录保持不变。'} 手动字体颜色在此比较视图中不显示。</p>`+v.paragraphs.map(p=>{const d=XuzhangDiff.diffText(p.before,p.text);return `<section id="version-para-${esc(p.id)}" class="version-paragraph ${p.type==='heading'?'version-heading':''}">${d.runs.map(r=>`<span class="${versionMarks&&r.added?'version-added':''}">${esc(r.text)}</span>`).join('')}${d.coarse&&versionMarks?'<small>长段落按改写范围标记，完整前后文见改动明细。</small>':''}</section>`}).join('')+`<p class="muted">${esc(v.limitations)}</p>`}
 else if(versionTab==='ideas'){const s=v.state;content=`<h3>作品目标</h3><p>${esc(s.blueprint.goal)}</p><h3>全篇思路与规则</h3><pre>${esc(versionValue(s.paper||{}))}</pre>${s.blueprint.nodes.map(n=>`<section class="card"><h3>${esc(n.part)}</h3><pre>${esc(versionValue(n))}</pre></section>`).join('')}<h3>决定与依据</h3>${s.knowledge.map(k=>`<section class="card"><h4>${esc(k.title)}</h4><pre>${esc(versionValue(k))}</pre></section>`).join('')}`}
 else content=v.changes.map(c=>`<details class="version-change" ${c.area==='正文'?'open':''}><summary>${esc(c.area)} · ${esc(c.label)}</summary><div class="bp-diff"><div><small>修改前</small><pre>${esc(versionValue(c.before))}</pre></div><div><small>修改后</small><pre>${esc(versionValue(c.after))}</pre></div></div></details>`).join('')||'<p>这两个版本之间没有内容变化。</p>';
 return summary+tabs+content;
}
function renderVersions(){const d=$('#modal');d.classList.add('version-dialog');d.innerHTML=`<div class="actions"><h2>修改阶段 · ${esc(versionView?.state.project?.name||'当前项目')}</h2>${btn('返回工作稿','close')}</div><div class="version-layout"><aside class="version-list"><p>每次保存都是可追查的阶段</p>${versionRows.map(r=>btn(`版本 ${r.revision} · ${r.title}`,'version-pick',`data-revision="${r.revision}" class="${r.revision===versionView?.revision?'primary':''}"`)).join('')}${versionCursor?btn('更早的阶段','version-more'):''}</aside><section class="version-content">${versionDetailHtml()}</section></div>`;if(!d.open)d.showModal()}
async function openVersions(ready){const id=currentId(),request=++versionRequest;try{const [rows,view]=await Promise.all([api('/api/version-history?project='+encodeURIComponent(id)),ready?Promise.resolve(ready):api('/api/version-history?project='+encodeURIComponent(id)+'&revision='+versions[id])]);if(request!==versionRequest||id!==currentId())return;versionRows=rows.items;versionCursor=rows.nextBefore;versionView=view;versionTab='text';versionMarks=true;renderVersions()}catch(e){toast(e.message)}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;if(action==='versions-open')return openVersions();if(!action.startsWith('version-'))return;const id=currentId(),request=++versionRequest;try{if(action==='version-pick'){const view=await api('/api/version-history?project='+encodeURIComponent(id)+'&revision='+Number(b.dataset.revision));if(request!==versionRequest||id!==currentId()||!$('#modal').open)return;versionView=view;versionMarks=true;renderVersions()}else if(action==='version-tab'){versionTab=b.dataset.tab;renderVersions()}else if(action==='version-marks'){versionMarks=!versionMarks;renderVersions()}else if(action==='version-more'){const rows=await api('/api/version-history?project='+encodeURIComponent(id)+'&before='+versionCursor);if(request!==versionRequest||id!==currentId()||!$('#modal').open)return;versionRows.push(...rows.items);versionCursor=rows.nextBefore;renderVersions()}}catch(err){toast(err.message)}});
$('#modal').addEventListener('close',()=>{versionRequest++;$('#modal').classList.remove('version-dialog')});
